data:
  class_path: data_loaders.sms_wsj.SmsWsjDataModule
  init_args:
    sms_wsj_dir: ~/datasets/sms_wsj/
    target: direct_path
    audio_time_len: [4.0, 4.0, null]
    batch_size: [2, 1]
    test_set: test
